/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BottomNav: typeof import('./components/Dashboard/BottomNav.vue')['default']
    DailyGraph: typeof import('./components/EnergyRecords/DailyGraph.vue')['default']
    GapGraph: typeof import('./components/EnergyRecords/GapGraph.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginPage: typeof import('./components/Dashboard/LoginPage.vue')['default']
    MaxMinGraph: typeof import('./components/EnergyRecords/MaxMinGraph.vue')['default']
    MonthlyGraph: typeof import('./components/EnergyRecords/MonthlyGraph.vue')['default']
    RawData: typeof import('./components/EnergyRecords/RawData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WeeklyGraph: typeof import('./components/EnergyRecords/WeeklyGraph.vue')['default']
  }
}
