/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Commodities/EnergyView': RouteRecordInfo<'/Commodities/EnergyView', '/Commodities/EnergyView', Record<never, never>, Record<never, never>>,
    '/Employees/AccountView': RouteRecordInfo<'/Employees/AccountView', '/Employees/AccountView', Record<never, never>, Record<never, never>>,
    '/Employees/Registration': RouteRecordInfo<'/Employees/Registration', '/Employees/Registration', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/Manipulations/Add/BenefitsEntry': RouteRecordInfo<'/Manipulations/Add/BenefitsEntry', '/Manipulations/Add/BenefitsEntry', Record<never, never>, Record<never, never>>,
    '/Manipulations/Edit/BenefitsUpdate': RouteRecordInfo<'/Manipulations/Edit/BenefitsUpdate', '/Manipulations/Edit/BenefitsUpdate', Record<never, never>, Record<never, never>>,
    '/PageNotFound': RouteRecordInfo<'/PageNotFound', '/PageNotFound', Record<never, never>, Record<never, never>>,
  }
}
